export const SECTIONS = [
  {
    id: "numerical",
    name: "Numerical Ability",
    duration: 40,
    color: "#00D4FF",
    questions: [
      {
        id: 1, topic: "LCM & HCF",
        text: "What is the sum of LCM and HCF of 5/18, 35/9 and 15/63?",
        options: ["1475/252", "1475/126", "625/252", "625/126"],
        answer: 1,
      },
      {
        id: 2, topic: "Fractions",
        text: "The reciprocal of a fraction is more than itself by 21/240. How much is the difference between the possible values of the fraction more than 2?",
        options: ["1/15", "1/16", "1/240", "1/256"],
        answer: 2,
      },
      {
        id: 3, topic: "Simple Interest",
        text: "A person invested ⅔ of his capital at 6%, ⅕ at 10% and the remainder at 15%. If his annual income is ₹3,600, the capital will be:",
        options: ["₹5,000", "₹2,500", "₹7,500", "₹45,000"],
        answer: 3,
      },
      {
        id: 4, topic: "Algebra",
        text: "If 8^(x+1) + 8^(1-x) = 20, then x = ?",
        options: ["¼, -¼", "½, -½", "⅓, -⅓", "⅕, -⅕"],
        answer: 2,
      },
      {
        id: 5, topic: "Percentage",
        text: "At an academic institution in 2016: 52 weekends, 30 days summer vacation (includes 4 weekends), Autumn & Winter breaks of 10+10 days each (1 weekend each), 14 special occasion holidays (1 Saturday, 1 Sunday). What was the percentage of holidays (correct to two decimal places)?",
        options: ["45.90%", "42.08%", "42.19%", "43.73%"],
        answer: 1,
      },
      {
        id: 6, topic: "Averages",
        text: "In a family of 10 adults and a few minors, average flour consumption is 12 kg. Average per adult is 15 kg and per minor is 7 kg. What is the number of minors?",
        options: ["6", "7", "5", "8"],
        answer: 0,
      },
      {
        id: 7, topic: "SI & CI",
        text: "A person lends 35% at 12.5% p.a., 50% at 10% p.a. and rest at 18% p.a. What is the approximate annual rate on the whole sum?",
        options: ["13%", "14.5%", "13.5%", "13.75%"],
        answer: 2,
      },
      {
        id: 8, topic: "Averages",
        text: "Average weight of 6 people increases from 24 to 31.5 kg when one leaves and a new person (60 kg) joins. Find the weight of person who left.",
        options: ["22.5 kg", "37.5 kg", "15 kg", "30 kg"],
        answer: 2,
      },
      {
        id: 9, topic: "Alloys & Mixtures",
        text: "Alloys A, B, C have Cu:Tin:Ni ratios 16:3:1, 15:3:2 and 14:5:1. If 10kg A, 15kg B, 50kg C are mixed, final Cu:Tin:Ni ratio is:",
        options: ["217:65:18", "217:65:81", "217:56:18", "127:65:18"],
        answer: 0,
      },
      {
        id: 10, topic: "Profit & Loss",
        text: "Rahul bought a watch (MRP ₹1,875) at 24% discount. Sold to Rohit at 28% profit. Rohit marked 25% above cost, sold to Mohit at 15% discount. Mohit marked 50% above cost. Rahul paid ₹28.5 extra than his initial price. At what % discount did Mohit sell?",
        options: ["35%", "50%", "45%", "40%"],
        answer: 3,
      },
      {
        id: 11, topic: "Time & Work",
        text: "If 210 km road is built by 540 workmen in 28 days, how many workmen are needed for 150 km in 18 days?",
        options: ["600", "300", "650", "450"],
        answer: 0,
      },
      {
        id: 12, topic: "Time Speed Distance",
        text: "P and Q are 42 km apart. Rohit and Mohit start from P at 6 km/h and 8 km/h. Mohit reaches Q, returns to meet Rohit at R. Find distance PR.",
        options: ["30 km", "36 km", "33 km", "27 km"],
        answer: 1,
      },
      {
        id: 13, topic: "Time Speed Distance",
        text: "A platform is 248 m long. An express train 127 m long travels at 150 km/h. In how many seconds does it clear the platform?",
        options: ["9 sec", "12 sec", "8 sec", "10 sec"],
        answer: 0,
      },
      {
        id: 14, topic: "Ratio & Proportion",
        text: "Nookaraju & Bhavana's salaries are in ratio 7:3. Bhavana gets +₹5,000, Nookaraju gets -₹1,000. New ratio is 1:1. What is Nookaraju's present salary?",
        options: ["₹8,500", "₹9,500", "₹15,000", "₹10,500"],
        answer: 1,
      },
      {
        id: 15, topic: "Mensuration",
        text: "The perimeter of a regular hexagon with area 21√3 cm² is:",
        options: ["12√3", "6√14", "9√3", "7√15"],
        answer: 1,
      },
    ],
  },
  {
    id: "verbal",
    name: "Verbal Ability",
    duration: 30,
    color: "#FF6B6B",
    questions: [
      {
        id: 1, topic: "Error Identification",
        text: "Identify the part with a grammatical error:\n'A university training enables a graduate seeing things as they are, and to disentangle a plethora of thoughts'",
        options: [
          "to disentangle a plethora of thoughts",
          "a graduate seeing things as they are",
          "to go right to the point",
          "A university training enables",
        ],
        answer: 1,
      },
      {
        id: 2, topic: "Error Identification",
        text: "Identify the part with an error:\n'I like to sit at the window for hours and see children playing in the park'",
        options: ["I like to sit at", "The window for hours", "In the park", "And see children playing"],
        answer: 3,
      },
      {
        id: 3, topic: "Sentence Correction",
        text: "Choose the phrase that best replaces the wrong phrase:\n'...one such rare achievement...is the ascending of Mount Everest by Hillary and Tenzing.'",
        options: ["Finer spirits", "By the dominant", "To have sought", "The ascent"],
        answer: 3,
      },
      {
        id: 4, topic: "Sentence Completion",
        text: "Fill blanks A, B, C, D:\n'Microsoft's (A) is a computer on every desk. Bill works to (B) his vision. He believes in hard work and (C). His beliefs helped establish his (D) in the industry.'",
        options: [
          "(A)Symbol (B)attain (C)investment (D)control",
          "(A)target (B)progress (C)frankness (D)importance",
          "(A)logo (B)believe (C)blessings (D)esteem",
          "(A)vision (B)achieve (C)competitiveness (D)monopoly",
        ],
        answer: 3,
      },
      {
        id: 5, topic: "Sentence Completion",
        text: "Fill blanks 1-4:\n'Mexico oak species, many are __(1)__. Arroyo oak faces a __(2)__ problem. Locals __(3)__ no seedlings had sprouted. Trees had __(4)__ stopped reproducing.'",
        options: [
          "1-threatened, 2-troubling, 3-noticed, 4-simply",
          "1-threaten, 2-troubling, 3-regarded, 4-simply",
          "1-threatening, 2-struggling, 3-recognized, 4-easily",
          "1-threatens, 2-agitating, 3-recognized, 4-directly",
        ],
        answer: 0,
      },
      {
        id: 6, topic: "Idioms & Phrases",
        text: "Fill idiom blanks:\n'The government (1) Sadhguru's ideas. Not received well in (2). We cannot (3) soil degradation. He has now (4) politicians to find solutions.'",
        options: [
          "(1)Reflected upon (2)certain quarters (3)Turn a blind eye (4)put the ball in the court",
          "(1)Reflected upon (2)A chunk of (3)Turned the other way (4)Gave up on",
          "(1)Reflected upon (2)A cross section (3)Turned the other way (4)Given up",
          "(1)Thought aloud (2)Certain section (3)Turn a deaf ear (4)Taken a back seat",
        ],
        answer: 0,
      },
      {
        id: 7, topic: "Idioms & Phrases",
        text: "Which sentence uses 'can't see the wood for the trees' correctly?",
        options: [
          "Sanya's obsessing over one doorknob — she can't see the wood in the trees.",
          "Marcus is so focused on product details that he can't see the wood for the trees when it comes to the overall needs of the company.",
          "The safety officer can't see the wood for the trees because she doesn't know which way to look.",
          "Raman always argues on silly topics — like he can't see the tree for the woods.",
        ],
        answer: 1,
      },
      {
        id: 8, topic: "Idioms & Phrases",
        text: "Arrange idioms for blanks:\n'People arrived ___ at the musical night. Alpana is usually able to ___. Before interval the event was ___. Despite all this Alpana was ___.\n(1)A dead duck (2)Bring the house down (3)Full of beans (4)dribs and drabs'",
        options: ["1-2-3-4", "4-2-3-1", "4-2-1-3", "1-3-4-2"],
        answer: 2,
      },
    ],
  },
  {
    id: "reasoning",
    name: "Reasoning Ability",
    duration: 30,
    color: "#FFD93D",
    questions: [
      {
        id: 1, topic: "Letter Series",
        text: "Identify the cluster that does NOT belong:\nCX, GT, EV, DW, HS, ZA, MN, UF\n(Hint: Each pair's letters should be equidistant from both ends of alphabet)",
        options: ["ZA", "UF", "HS", "MN"],
        answer: 2,
      },
      {
        id: 2, topic: "Letter Analogy",
        text: "Three pairs follow the same pattern. Which is the ODD one out?\n1. TMKOLFXOY : TOMKLFXOY\n2. PVMSYGCXN : VSPMYCGNX\n3. XDSWZOIVK : XWSDZIKOV\n4. FCHVOTFGW : VHFCOFGTW",
        options: [
          "TMKOLFXOY : TOMKLFXOY",
          "PVMSYGCXN : VSPMYCGNX",
          "XDSWZOIVK : XWSDZIKOV",
          "FCHVOTFGW : VHFCOFGTW",
        ],
        answer: 0,
      },
      {
        id: 3, topic: "Blood Relations",
        text: "Code: P&Q=P is son of Q | P@Q=P is mother of Q | P%Q=P is brother of Q | P#Q=P is husband of Q\n\nHow is K related to Q?\nExpression: K % G & T # V @ S @ N % Q",
        options: ["Father", "Father's brother", "Mother's brother", "Brother"],
        answer: 2,
      },
      {
        id: 4, topic: "Age Problems",
        text: "20 years ago Mohita was 22 years old. How old was she X years ago?",
        options: ["X – 42", "42", "42 – X", "62 – X"],
        answer: 2,
      },
      {
        id: 5, topic: "Statement & Course of Action",
        text: "Statement: A student was caught exploding crackers on hostel campus despite warnings.\n\nCourse I: Take away crackers and warn not to repeat.\nCourse II: Severely punish the student.",
        options: [
          "Either I or II follows",
          "Only II follows",
          "Neither I nor II follows",
          "Only I follows",
        ],
        answer: 0,
      },
      {
        id: 6, topic: "Statements & Conclusion",
        text: "What is the difference between p (total males) and q (total females) in a family?\n\nSt. I: Vipraja has six daughters who have a brother. Vipraja is Shantanu's wife.\nSt. II: Shantanu is father of six daughters. Kiran's mother Vipraja is married to Shantanu. Khan is male.",
        options: [
          "Statement I alone is sufficient",
          "Either I or II alone is sufficient",
          "Both I and II together are necessary",
          "Statement II alone is sufficient",
        ],
        answer: 0,
      },
    ],
  },
  {
    id: "advanced_quant",
    name: "Advanced Quantitative",
    duration: 35,
    color: "#6BCB77",
    questions: [
      {
        id: 1, topic: "Quadratic Equations",
        text: "If (1 + λ²)x² + 2λcx + (c² - a²) = 0 has equal roots, then a²(1 + λ²) = ?",
        options: ["c²", "-2", "a²", "-4"],
        answer: 0,
      },
      {
        id: 2, topic: "Permutations & Combinations",
        text: "A five-digit number using digits 1,2,3,4,5 (each exactly once) divisible by 4. How many such numbers exist?",
        options: ["4", "6", "8", "12"],
        answer: 1,
      },
      {
        id: 3, topic: "Surds & Indices",
        text: "What is the value of x?\n4 + 4√(x−1) = 2√(x+1)",
        options: ["1", "2", "3", "4"],
        answer: 0,
      },
      {
        id: 4, topic: "Linear Inequations",
        text: "Which points lie in the region: x ≥ 1, y ≥ 1 and x + y ≤ 6?",
        options: ["(4,2) only", "(3,2) only", "Both (2,5) & (4,2)", "(2,5) only"],
        answer: 2,
      },
      {
        id: 5, topic: "Quadratic Equations",
        text: "(k+3)x² − 10(k+3)x + 15(k+9) = 0, k ≠ −3, has equal roots. Find k.",
        options: ["3", "6", "9", "12"],
        answer: 1,
      },
      {
        id: 6, topic: "Data Interpretation",
        text: "Find the ratio of the average sale of all branches for the years 2020 and 2021:",
        options: ["80:81", "66.5:81", "88:76.5", "76.5:82"],
        answer: 3,
      },
      {
        id: 7, topic: "Mensuration",
        text: "A metallic solid cube (side 4 cm) is melted into a hollow sphere of internal radius 3 cm. What is the external radius?",
        options: ["(24/π + 27)^(1/3)", "(48/π + 27)^(1/3)", "(24/π + 9)^(1/3)", "(48/π + 9)^(1/3)"],
        answer: 1,
      },
    ],
  },
  {
    id: "advanced_logical",
    name: "Advanced Logical",
    duration: 35,
    color: "#C77DFF",
    questions: [
      {
        id: 1, topic: "Decision Making",
        text: "Screenplay needs: average-sized actress, age 45-50, big frame, grey hair, large blue eyes, fair skin, smiling face. Candidate has: black hair, big blue eyes, fair skin, in her thirties, medium build. Will she be selected?",
        options: ["Selected", "Not Selected", "On probation", "Need more info"],
        answer: 1,
      },
      {
        id: 2, topic: "Logical Deduction",
        text: "Numbers: 1=Amabad 2=Domabad 3=Taimabad 4=Chomabad 5=Pemabad 6=Chamabad.\n1 likes Chamabad. 3&4 like Pemabad. 6&1 like Taimabad, Pemabad, Domabad.\n\nWhich number likes Pemabad & Taimabad but NOT Chamabad?",
        options: ["1", "3", "4", "6"],
        answer: 3,
      },
      {
        id: 3, topic: "Coding-Decoding",
        text: "In a code language, JAVA is written as JVAA. How will MAWAA be written?",
        options: ["MAAAW", "MWAAA", "AWAAM", "WMAAA"],
        answer: 1,
      },
      {
        id: 4, topic: "Coding-Decoding",
        text: "SUM = NLVTTR, LATE = FDUSZMK. How will ROAST be coded?",
        options: ["SQPMBZTRUS", "UTBPSSRZNQ", "USTRBZPNSQ", "ZPNSQUSTRB"],
        answer: 2,
      },
      {
        id: 5, topic: "Statement & Arguments",
        text: "Statement: Each institute in India should be linked with an incubation centre.\n\nArg I: Students will be aware of start-ups and their societal benefit.\nArg II: More start-ups will help build the nation's economy.",
        options: [
          "Neither I nor II is strong",
          "Argument II is strong",
          "Both I and II are strong",
          "Argument I is strong",
        ],
        answer: 3,
      },
      {
        id: 6, topic: "Statement & Arguments",
        text: "Statement: Schools should encourage extra-curricular activities along with academics.\n\nArg I: Sports is a good career option.\nArg II: Extra-curriculars enhance learning abilities.\nArg III: Extra-curriculars help build skills.",
        options: [
          "Argument I is strong",
          "Arguments I, II and III are strong",
          "Argument III is strong",
          "Argument II is strong",
        ],
        answer: 3,
      },
    ],
  },
];

export const SECTION_ORDER = SECTIONS.map((s) => s.id);
